import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Advance medical center",
  description: "Generated by create next app",
 openGraph: {
    title: 'Advance medical center',
    description: 'Your trusted partner for expert medical imaging readings.',
    url: 'https://advance-medical-center.vercel.app/',
    siteName: 'Advance medical center',
    images: [
      {
        url: '/medical-center/public/favicon.ico',
        width: 1200,
        height: 630,
        alt: 'Advance medical center',
        type: 'image/favicon.ico',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
